"""Added pull request tables

Revision ID: 5a18948025f6
Revises:
Create Date: 2026-04-19 11:24:46.739418

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a18948025f6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pull_request",
        sa.Column("pr_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("pr_number"),
    )
    op.create_table(
        "pull_request_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pr_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("MERGED", "CLOSED", "DRAFT", "READY_FOR_REVIEW", name="pullrequeststatus"),
            nullable=False,
        ),
        sa.Column("pr_updated_at", sa.DateTime(), nullable=False),
        sa.Column("head_sha", sa.String(), nullable=False),
        sa.Column("head_ref", sa.String(), nullable=False),
        sa.Column("base_sha", sa.String(), nullable=False),
        sa.Column("base_ref", sa.String(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("sender_login", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pr_number"],
            ["pull_request.pr_number"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pull_request_state_pr_updated_at"),
        "pull_request_state",
        ["pr_updated_at"],
        unique=False,
    )
    op.create_table(
        "pull_request_review_change",
        sa.Column("pr_state_id", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("DISMISSED", "APPROVED", "CHANGES_REQUESTED", name="reviewstate"),
            nullable=False,
        ),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("reviewer_id", sa.Integer(), nullable=False),
        sa.Column("reviewer_login", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pr_state_id"],
            ["pull_request_state.id"],
        ),
        sa.PrimaryKeyConstraint("pr_state_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pull_request_review_change")
    op.drop_index(op.f("ix_pull_request_state_pr_updated_at"), table_name="pull_request_state")
    op.drop_table("pull_request_state")
    op.drop_table("pull_request")
    # ### end Alembic commands ###
