"""Adding event processing

Revision ID: 5842845c83bc
Revises: 5a18948025f6
Create Date: 2026-04-19 12:50:54.549636

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5842845c83bc"
down_revision: str | None = "5a18948025f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pull_request_changed_event",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("pr_updated_at", sa.DateTime(), nullable=False),
        sa.Column("pr_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pr_number"],
            ["pull_request.pr_number"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("pull_request", sa.Column("repo_name", sa.String(), nullable=False))
    op.add_column("pull_request", sa.Column("org", sa.String(), nullable=False))
    op.add_column("pull_request", sa.Column("branch_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pull_request", "branch_name")
    op.drop_column("pull_request", "org")
    op.drop_column("pull_request", "repo_name")
    op.drop_table("pull_request_changed_event")
    # ### end Alembic commands ###
